apiVersion: batch/v1
kind: Job
metadata:
  name: batchjobs
spec:
  completions: 100
  parallelism: 10
  template:
    metadata:
      labels:
        app: fake-pod
    spec:
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - kperf-virtualnodes
      # A taints was added to an automatically created Node.
      # You can remove taints of Node or add this tolerations.
      tolerations:
      - key: "kperf.io/nodepool"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: fake-container
        image: fake-image
